### ISSUE TITLE
[repl] unable to bot.say on longer code.

### ISSUE THREAD

**Issue by Jan200101** [irdumbs/Dumb-Cogs#35]
Using just

`bot.say('message')`

yields the correct results but doing stuff like

`for x in server.emojis:
    bot.say(x.name)`

does not seem to work.

A slight workaround is using print() instead but print() does not allow for embeds

**Comment by Chovin** [comment]
This is because the repl only automatically awaits single line expressions.
bot.say is a coroutine.

If you want to do anything more complicated with coros, I'd recommend putting them into their own functions first.

here's an example I use often when I'm debugging with repl
```py
async def getm(id):
    global m
    m = await bot.get_message(channel, id)
```

then as a single expression: `getm(id)`
