### ISSUE TITLE
[Welcome] Bot role not works with permissions

### ISSUE THREAD

**Issue by fixator10** [irdumbs/Dumb-Cogs#42]
When adding bot with permissions (Discord-Managed role, `&permissions=int`) bot's role not assign with error
```
welcome.py: added %role% role to bot, %bot%
welcome.py: unable to add %role% role to %bot%. Role was deleted, network error, or lacking permissions
```

But on adding bot without predefined role/permissions (without `&permissions=int` arg in URL), role assigns normally

Bot has access to manage roles

**Comment by ghost** [comment]
Issue caused by add_role command, which tries to get list of roles from bot, then add new role to this list and then replace_roles with the new list.
But managed role is not yet on the list when add_role is running, so replace_role tries to replace list of role with Bot role only, and Managed role is not replaceable.

Quick and dirty fix is to add 5 seconds sleep before assigning roles to bot.
Or think of something more beautiful :D

**Comment by Chovin** [comment]
not sure I understand but I'll add a 5 second fallback in case
